// Genererad från TimeEdit_2026-08-12_13_40.xlsx. Ändra inte utan att kontrollera mot källfilen.
export const SCHEDULE_META = {
  "appName": "Polisutbildningen Malmö – HT26",
  "scheduleTitle": "Schema T5 HT2026",
  "sourceFile": "TimeEdit_2026-08-12_13_40.xlsx",
  "sourceExportedAt": "2026-08-12 13:40",
  "sourcePeriod": "2026-08-12 - 2027-01-15",
  "eventPeriod": "2026-08-25 - 2027-01-15",
  "selectedObjects": "DP132A-HT2025-DP132, DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2, DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4, DP151A-HT2026-DT151, DP152A-HT2026-DP152",
  "groups": [
    "BG1",
    "BG2",
    "BG3",
    "BG4"
  ],
  "eventCount": 122
};

export const TERM_INFO = {
  "heading": "Inför sista terminen",
  "introduction": "Under HT26 inleds termin 5 med en trafikkurs, följd av uppsatsarbete. Parallellt fortsätter återstående tjänstefärdighetsmoment.",
  "courses": [
    {
      "code": "DP151A",
      "name": "Trafikkurs",
      "responsible": "Peter Hellqvist",
      "description": "Trafikjuridik, trafikolyckor och att skriva ordningsbot."
    },
    {
      "code": "DP152A",
      "name": "Uppsats",
      "responsible": "Malin Mc Glinn",
      "description": "Uppsatsarbete efter trafikkursen."
    },
    {
      "code": "DP132A",
      "name": "Tjänstefärdighetsmoment",
      "responsible": "",
      "description": "Återstående tjänstefärdighetsmoment, bland annat arbete med folksamlingar och agerande under pågående dödligt våld."
    }
  ],
  "campusWeeks": [
    {
      "label": "NSV 1",
      "week": 36,
      "year": 2026
    },
    {
      "label": "NSV 2",
      "week": 40,
      "year": 2026
    },
    {
      "label": "NSV 3",
      "week": 45,
      "year": 2026
    },
    {
      "label": "NSV 4",
      "week": 51,
      "year": 2026
    },
    {
      "label": "NSV 5",
      "week": 2,
      "year": 2027
    }
  ],
  "graduation": "Examen planeras till kalendervecka 2. Exakt dag är ännu inte fastställd eftersom den beror på tillgång till lokal för ceremonin.",
  "groupMembers": {
    "BG1": [
      "Jennifer",
      "Helene",
      "Hanna",
      "Ellen"
    ],
    "BG2": [
      "Julia",
      "Adrian",
      "Emanuel",
      "Sara",
      "Cornelia"
    ],
    "BG3": [
      "Jimmy",
      "Alexander",
      "Mattias",
      "Bastian"
    ],
    "BG4": [
      "Vegard",
      "Fredrik",
      "Dennis",
      "Johan"
    ]
  },
  "sourceLabel": "Information inför termin 5, HT26"
};

export const SCHEDULE_DATA = [
  {
    "id": "te-7",
    "sourceRow": 7,
    "week": 35,
    "weekday": "Tisdag",
    "date": "2026-08-25",
    "startTime": "10:15",
    "endDate": "2026-08-25",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Dk1. Polkon FTM",
    "course": "Dk1. Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Resurslektion",
    "momentText": "",
    "momentNumber": "8",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-8",
    "sourceRow": 8,
    "week": 35,
    "weekday": "Onsdag",
    "date": "2026-08-26",
    "startTime": "10:15",
    "endDate": "2026-08-26",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Dk1. Polkon FTM",
    "course": "Dk1. Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Omexamination 1",
    "momentText": "",
    "momentNumber": "8",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-9",
    "sourceRow": 9,
    "week": 35,
    "weekday": "Fredag",
    "date": "2026-08-28",
    "startTime": "10:15",
    "endDate": "2026-08-28",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Dk1. Polkon FTM",
    "course": "Dk1. Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Omexamination 2",
    "momentText": "",
    "momentNumber": "8",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-10",
    "sourceRow": 10,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "08:00",
    "endDate": "2026-08-31",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-11",
    "sourceRow": 11,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "10:15",
    "endDate": "2026-08-31",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Målfokus",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-12",
    "sourceRow": 12,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "10:15",
    "endDate": "2026-08-31",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1211G1",
    "locations": "Grepphall, Öppen yta",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-13",
    "sourceRow": 13,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "13:15",
    "endDate": "2026-08-31",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1211G1",
    "locations": "Grepphall, Öppen yta",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-14",
    "sourceRow": 14,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "13:15",
    "endDate": "2026-08-31",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Målfokus",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-15",
    "sourceRow": 15,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "15:15",
    "endDate": "2026-08-31",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-16",
    "sourceRow": 16,
    "week": 36,
    "weekday": "Måndag",
    "date": "2026-08-31",
    "startTime": "15:15",
    "endDate": "2026-08-31",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-17",
    "sourceRow": 17,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "08:00",
    "endDate": "2026-09-01",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-18",
    "sourceRow": 18,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "08:15",
    "endDate": "2026-09-01",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Rättssäker dokumentation DURTvå",
    "course": "Rättssäker dokumentation DURTvå",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Slutredovisning",
    "momentText": "",
    "momentNumber": "14",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-19",
    "sourceRow": 19,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "13:15",
    "endDate": "2026-09-01",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Rörelse",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-20",
    "sourceRow": 20,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "13:15",
    "endDate": "2026-09-01",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-21",
    "sourceRow": 21,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "15:15",
    "endDate": "2026-09-01",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-22",
    "sourceRow": 22,
    "week": 36,
    "weekday": "Tisdag",
    "date": "2026-09-01",
    "startTime": "15:15",
    "endDate": "2026-09-01",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Rörelse",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-23",
    "sourceRow": 23,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "08:00",
    "endDate": "2026-09-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-24",
    "sourceRow": 24,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "08:15",
    "endDate": "2026-09-02",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1222H1",
    "locations": "Lärosal / ALC",
    "type": "Lektion",
    "momentText": "Vägspärr, grunder",
    "momentNumber": "5:1",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-25",
    "sourceRow": 25,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "13:15",
    "endDate": "2026-09-02",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-26",
    "sourceRow": 26,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "13:15",
    "endDate": "2026-09-02",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Sekundär hand",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-27",
    "sourceRow": 27,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "15:15",
    "endDate": "2026-09-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Sekundär hand",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-28",
    "sourceRow": 28,
    "week": 36,
    "weekday": "Onsdag",
    "date": "2026-09-02",
    "startTime": "15:15",
    "endDate": "2026-09-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-29",
    "sourceRow": 29,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "08:00",
    "endDate": "2026-09-03",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-30",
    "sourceRow": 30,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "08:15",
    "endDate": "2026-09-03",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Akutsjukvård",
    "course": "Akutsjukvård",
    "locationIds": "K4:12A304, K4:12B301, K4:12E301",
    "locations": "Lgh 2, Lgh 3, Lgh 3",
    "type": "Lektion",
    "momentText": "Scenarioövningar",
    "momentNumber": "9",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-31",
    "sourceRow": 31,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "13:15",
    "endDate": "2026-09-03",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1211G1",
    "locations": "Grepphall, Öppen yta",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-32",
    "sourceRow": 32,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "13:15",
    "endDate": "2026-09-03",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-33",
    "sourceRow": 33,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "15:15",
    "endDate": "2026-09-03",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-34",
    "sourceRow": 34,
    "week": 36,
    "weekday": "Torsdag",
    "date": "2026-09-03",
    "startTime": "15:15",
    "endDate": "2026-09-03",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1211G1",
    "locations": "Grepphall, Öppen yta",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:3",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-35",
    "sourceRow": 35,
    "week": 36,
    "weekday": "Fredag",
    "date": "2026-09-04",
    "startTime": "08:00",
    "endDate": "2026-09-04",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-36",
    "sourceRow": 36,
    "week": 36,
    "weekday": "Fredag",
    "date": "2026-09-04",
    "startTime": "08:15",
    "endDate": "2026-09-04",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "KR:1103N2",
    "locations": "Lärosal",
    "type": "Lektion",
    "momentText": "Kropp, röst och makt",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-37",
    "sourceRow": 37,
    "week": 37,
    "weekday": "Måndag",
    "date": "2026-09-07",
    "startTime": "08:00",
    "endDate": "2026-09-07",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-38",
    "sourceRow": 38,
    "week": 37,
    "weekday": "Tisdag",
    "date": "2026-09-08",
    "startTime": "08:00",
    "endDate": "2026-09-08",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-39",
    "sourceRow": 39,
    "week": 37,
    "weekday": "Onsdag",
    "date": "2026-09-09",
    "startTime": "08:00",
    "endDate": "2026-09-09",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-40",
    "sourceRow": 40,
    "week": 37,
    "weekday": "Torsdag",
    "date": "2026-09-10",
    "startTime": "08:00",
    "endDate": "2026-09-10",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-41",
    "sourceRow": 41,
    "week": 37,
    "weekday": "Fredag",
    "date": "2026-09-11",
    "startTime": "08:00",
    "endDate": "2026-09-11",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Terminsstart: lokaler bokas endast för undervisning",
    "title": "Terminsstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-42",
    "sourceRow": 42,
    "week": 38,
    "weekday": "Onsdag",
    "date": "2026-09-16",
    "startTime": "13:15",
    "endDate": "2026-09-16",
    "endTime": "16:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Att ge och få återkoppling",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-43",
    "sourceRow": 43,
    "week": 39,
    "weekday": "Onsdag",
    "date": "2026-09-23",
    "startTime": "08:15",
    "endDate": "2026-09-23",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Examination Trafikförordningen (Moment 12 PNF)",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "Examination",
    "momentText": "Examination Trafikförordningen (Moment 12 PNF)",
    "momentNumber": "12",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-44",
    "sourceRow": 44,
    "week": 40,
    "weekday": "Måndag",
    "date": "2026-09-28",
    "startTime": "09:15",
    "endDate": "2026-09-28",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1222H1",
    "locations": "Lärosal / ALC",
    "type": "Lektion",
    "momentText": "Sök i terräng. Rek/obs/säk",
    "momentNumber": "5:2",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-45",
    "sourceRow": 45,
    "week": 40,
    "weekday": "Måndag",
    "date": "2026-09-28",
    "startTime": "13:15",
    "endDate": "2026-09-28",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Rättssäker dokumentation DURTvå",
    "course": "Rättssäker dokumentation DURTvå",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Lektion",
    "momentText": "Kapellskäret",
    "momentNumber": "15",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-46",
    "sourceRow": 46,
    "week": 40,
    "weekday": "Tisdag",
    "date": "2026-09-29",
    "startTime": "13:15",
    "endDate": "2026-09-29",
    "endTime": "15:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1029E1",
    "locations": "Grepphall",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:4",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-47",
    "sourceRow": 47,
    "week": 40,
    "weekday": "Tisdag",
    "date": "2026-09-29",
    "startTime": "15:15",
    "endDate": "2026-09-29",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Akutsjukvård",
    "course": "Akutsjukvård",
    "locationIds": "K4:12C201",
    "locations": "Grepphall",
    "type": "Lektion",
    "momentText": "Barn-HLR",
    "momentNumber": "10",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-48",
    "sourceRow": 48,
    "week": 40,
    "weekday": "Onsdag",
    "date": "2026-09-30",
    "startTime": "13:15",
    "endDate": "2026-09-30",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:4",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-49",
    "sourceRow": 49,
    "week": 40,
    "weekday": "Onsdag",
    "date": "2026-09-30",
    "startTime": "13:15",
    "endDate": "2026-09-30",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012K3",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Precision",
    "momentNumber": "5:4",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-50",
    "sourceRow": 50,
    "week": 40,
    "weekday": "Onsdag",
    "date": "2026-09-30",
    "startTime": "15:15",
    "endDate": "2026-09-30",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Precision",
    "momentNumber": "5:4",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-51",
    "sourceRow": 51,
    "week": 40,
    "weekday": "Onsdag",
    "date": "2026-09-30",
    "startTime": "15:15",
    "endDate": "2026-09-30",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:4",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-52",
    "sourceRow": 52,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "08:15",
    "endDate": "2026-10-01",
    "endTime": "09:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Lektion",
    "momentText": "Lågfart tätort",
    "momentNumber": "13",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-53",
    "sourceRow": 53,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "08:15",
    "endDate": "2026-10-01",
    "endTime": "10:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Låg färdigställning/Drag från hölster",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-54",
    "sourceRow": 54,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "09:00",
    "endDate": "2026-10-01",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Lågfart tätort",
    "momentNumber": "13",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-55",
    "sourceRow": 55,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "10:15",
    "endDate": "2026-10-01",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1006N4",
    "locations": "Arrest",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-56",
    "sourceRow": 56,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "13:15",
    "endDate": "2026-10-01",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Låg färdigställning/Drag från hölster",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-57",
    "sourceRow": 57,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "13:15",
    "endDate": "2026-10-01",
    "endTime": "14:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Lektion",
    "momentText": "Lågfart tätort",
    "momentNumber": "13",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-58",
    "sourceRow": 58,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "14:00",
    "endDate": "2026-10-01",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Lågfart tätort",
    "momentNumber": "13",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-59",
    "sourceRow": 59,
    "week": 40,
    "weekday": "Torsdag",
    "date": "2026-10-01",
    "startTime": "15:15",
    "endDate": "2026-10-01",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1006N4",
    "locations": "Arrest",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-60",
    "sourceRow": 60,
    "week": 40,
    "weekday": "Fredag",
    "date": "2026-10-02",
    "startTime": "13:15",
    "endDate": "2026-10-02",
    "endTime": "15:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1222H1",
    "locations": "Lärosal / ALC",
    "type": "AMF",
    "momentText": "Juridik metod",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-61",
    "sourceRow": 61,
    "week": 40,
    "weekday": "Fredag",
    "date": "2026-10-02",
    "startTime": "15:15",
    "endDate": "2026-10-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-62",
    "sourceRow": 62,
    "week": 40,
    "weekday": "Fredag",
    "date": "2026-10-02",
    "startTime": "15:15",
    "endDate": "2026-10-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:5",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-63",
    "sourceRow": 63,
    "week": 44,
    "weekday": "Lördag",
    "date": "2026-10-31",
    "startTime": "00:00",
    "endDate": "2026-11-01",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Alla helgons dag",
    "title": "Alla helgons dag",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-64",
    "sourceRow": 64,
    "week": 45,
    "weekday": "Måndag",
    "date": "2026-11-02",
    "startTime": "10:15",
    "endDate": "2026-11-02",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-65",
    "sourceRow": 65,
    "week": 45,
    "weekday": "Måndag",
    "date": "2026-11-02",
    "startTime": "10:15",
    "endDate": "2026-11-02",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-66",
    "sourceRow": 66,
    "week": 45,
    "weekday": "Måndag",
    "date": "2026-11-02",
    "startTime": "13:15",
    "endDate": "2026-11-02",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Rättssäker dokumentation DURTvå",
    "course": "Rättssäker dokumentation DURTvå",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Lektion",
    "momentText": "Inför examination",
    "momentNumber": "16",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-67",
    "sourceRow": 67,
    "week": 45,
    "weekday": "Tisdag",
    "date": "2026-11-03",
    "startTime": "10:15",
    "endDate": "2026-11-03",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-68",
    "sourceRow": 68,
    "week": 45,
    "weekday": "Tisdag",
    "date": "2026-11-03",
    "startTime": "10:15",
    "endDate": "2026-11-03",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-69",
    "sourceRow": 69,
    "week": 45,
    "weekday": "Tisdag",
    "date": "2026-11-03",
    "startTime": "13:15",
    "endDate": "2026-11-03",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1222H1",
    "locations": "Lärosal / ALC",
    "type": "AMF",
    "momentText": "Planspel",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-70",
    "sourceRow": 70,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "08:15",
    "endDate": "2026-11-04",
    "endTime": "09:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Examination",
    "momentText": "Lågfart tätort",
    "momentNumber": "14",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-71",
    "sourceRow": 71,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "09:00",
    "endDate": "2026-11-04",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Examination",
    "momentText": "Lågfart tätort",
    "momentNumber": "14",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-72",
    "sourceRow": 72,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "10:15",
    "endDate": "2026-11-04",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1212J1",
    "locations": "Grepphall, Mjuk övningsmiljö",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-73",
    "sourceRow": 73,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "13:15",
    "endDate": "2026-11-04",
    "endTime": "14:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Examination",
    "momentText": "Lågfart tätort",
    "momentNumber": "14",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-74",
    "sourceRow": 74,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "13:15",
    "endDate": "2026-11-04",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1212J1",
    "locations": "Grepphall, Mjuk övningsmiljö",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-75",
    "sourceRow": 75,
    "week": 45,
    "weekday": "Onsdag",
    "date": "2026-11-04",
    "startTime": "14:00",
    "endDate": "2026-11-04",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Examination",
    "momentText": "Lågfart tätort",
    "momentNumber": "14",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-76",
    "sourceRow": 76,
    "week": 45,
    "weekday": "Torsdag",
    "date": "2026-11-05",
    "startTime": "08:15",
    "endDate": "2026-11-05",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1203E2, KR:1207E2",
    "locations": "Lärosal, Lärosal",
    "type": "Examination",
    "momentText": "",
    "momentNumber": "5:8",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-77",
    "sourceRow": 77,
    "week": 45,
    "weekday": "Torsdag",
    "date": "2026-11-05",
    "startTime": "10:15",
    "endDate": "2026-11-05",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Sammanfattning",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-78",
    "sourceRow": 78,
    "week": 45,
    "weekday": "Torsdag",
    "date": "2026-11-05",
    "startTime": "10:15",
    "endDate": "2026-11-05",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1212J1",
    "locations": "Grepphall, Mjuk övningsmiljö",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-79",
    "sourceRow": 79,
    "week": 45,
    "weekday": "Torsdag",
    "date": "2026-11-05",
    "startTime": "13:15",
    "endDate": "2026-11-05",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1208J1, KR:1212J1",
    "locations": "Grepphall, Mjuk övningsmiljö",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-80",
    "sourceRow": 80,
    "week": 45,
    "weekday": "Torsdag",
    "date": "2026-11-05",
    "startTime": "13:15",
    "endDate": "2026-11-05",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Lektion",
    "momentText": "Sammanfattning",
    "momentNumber": "5:6",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-81",
    "sourceRow": 81,
    "week": 45,
    "weekday": "Fredag",
    "date": "2026-11-06",
    "startTime": "13:15",
    "endDate": "2026-11-06",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012K3",
    "locations": "Skjutbana",
    "type": "Examination",
    "momentText": "Behörighetsprovet",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-82",
    "sourceRow": 82,
    "week": 45,
    "weekday": "Fredag",
    "date": "2026-11-06",
    "startTime": "15:15",
    "endDate": "2026-11-06",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012K3",
    "locations": "Skjutbana",
    "type": "Examination",
    "momentText": "Behörighetsprovet",
    "momentNumber": "5:7",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-83",
    "sourceRow": 83,
    "week": 46,
    "weekday": "Måndag",
    "date": "2026-11-09",
    "startTime": "08:00",
    "endDate": "2026-11-09",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Mitterminstart: lokaler bokas endast för undervisning",
    "title": "Mitterminstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-84",
    "sourceRow": 84,
    "week": 46,
    "weekday": "Tisdag",
    "date": "2026-11-10",
    "startTime": "08:00",
    "endDate": "2026-11-10",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Mitterminstart: lokaler bokas endast för undervisning",
    "title": "Mitterminstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-85",
    "sourceRow": 85,
    "week": 46,
    "weekday": "Onsdag",
    "date": "2026-11-11",
    "startTime": "08:00",
    "endDate": "2026-11-11",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Mitterminstart: lokaler bokas endast för undervisning",
    "title": "Mitterminstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-86",
    "sourceRow": 86,
    "week": 46,
    "weekday": "Torsdag",
    "date": "2026-11-12",
    "startTime": "08:00",
    "endDate": "2026-11-12",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Mitterminstart: lokaler bokas endast för undervisning",
    "title": "Mitterminstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-87",
    "sourceRow": 87,
    "week": 46,
    "weekday": "Fredag",
    "date": "2026-11-13",
    "startTime": "08:00",
    "endDate": "2026-11-13",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "Mitterminstart: lokaler bokas endast för undervisning",
    "title": "Mitterminstart: lokaler bokas endast för undervisning",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "notice"
  },
  {
    "id": "te-88",
    "sourceRow": 88,
    "week": 50,
    "weekday": "Onsdag",
    "date": "2026-12-09",
    "startTime": "13:15",
    "endDate": "2026-12-09",
    "endTime": "15:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Inför dödsbudsövning",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-89",
    "sourceRow": 89,
    "week": 51,
    "weekday": "Måndag",
    "date": "2026-12-14",
    "startTime": "08:15",
    "endDate": "2026-12-14",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "Körgård",
    "locations": "Körgård",
    "type": "AMF",
    "momentText": "Praktisk övning",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-90",
    "sourceRow": 90,
    "week": 51,
    "weekday": "Måndag",
    "date": "2026-12-14",
    "startTime": "13:15",
    "endDate": "2026-12-14",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0",
    "locations": "Skjutbana",
    "type": "Resurstid 1",
    "momentText": "",
    "momentNumber": "5:8",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-91",
    "sourceRow": 91,
    "week": 51,
    "weekday": "Måndag",
    "date": "2026-12-14",
    "startTime": "13:15",
    "endDate": "2026-12-14",
    "endTime": "15:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012K3",
    "locations": "Skjutbana",
    "type": "Resurstid 1",
    "momentText": "",
    "momentNumber": "5:8",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-92",
    "sourceRow": 92,
    "week": 51,
    "weekday": "Måndag",
    "date": "2026-12-14",
    "startTime": "15:15",
    "endDate": "2026-12-14",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:9",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-93",
    "sourceRow": 93,
    "week": 51,
    "weekday": "Måndag",
    "date": "2026-12-14",
    "startTime": "15:15",
    "endDate": "2026-12-14",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1120N2",
    "locations": "Radiosal",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:9",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-94",
    "sourceRow": 94,
    "week": 51,
    "weekday": "Tisdag",
    "date": "2026-12-15",
    "startTime": "08:15",
    "endDate": "2026-12-15",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1103N2, KR:1112G2",
    "locations": "Lärosal, Flexrum",
    "type": "PDV",
    "momentText": "Dag 1. Introduktion",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-95",
    "sourceRow": 95,
    "week": 51,
    "weekday": "Tisdag",
    "date": "2026-12-15",
    "startTime": "10:15",
    "endDate": "2026-12-15",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1103N2",
    "locations": "Lärosal",
    "type": "PDV",
    "momentText": "Dag 1. Planspel",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-96",
    "sourceRow": 96,
    "week": 51,
    "weekday": "Tisdag",
    "date": "2026-12-15",
    "startTime": "13:15",
    "endDate": "2026-12-15",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "K4:12A101, K4:12A201, K4:12A304, K4:12B101, K4:12B201, K4:12B301, K4:12C101, K4:12C201, K4:12C305, K4:12D101, K4:12E301, K4:12H101, K4:12H201, K4:12J301, K4:12K204",
    "locations": "Butik, Reception, Lgh 2, Polisstation, Övningsmiljö Parkbänk, Lgh 3, Övningsmiljö Gågata, Grepphall, Övningsmiljö Trapphus, Pub, Lgh 3, Start/Skytterum, Flexrum, FX-lägenhet, FX-lägenhet",
    "type": "PDV",
    "momentText": "Dag 1. Formell metodträning",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-97",
    "sourceRow": 97,
    "week": 51,
    "weekday": "Onsdag",
    "date": "2026-12-16",
    "startTime": "08:15",
    "endDate": "2026-12-16",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1103N2",
    "locations": "Lärosal",
    "type": "PDV",
    "momentText": "Dag 2. Begreppsteori",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-98",
    "sourceRow": 98,
    "week": 51,
    "weekday": "Onsdag",
    "date": "2026-12-16",
    "startTime": "10:15",
    "endDate": "2026-12-16",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "KR:1103N2",
    "locations": "Lärosal",
    "type": "PDV",
    "momentText": "Dag 2. Föreläsning: Jokela",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-99",
    "sourceRow": 99,
    "week": 51,
    "weekday": "Onsdag",
    "date": "2026-12-16",
    "startTime": "13:15",
    "endDate": "2026-12-16",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Taktik",
    "course": "Polkon Taktik",
    "locationIds": "K4:12A101, K4:12A201, K4:12A304, K4:12B101, K4:12B201, K4:12B301, K4:12C101, K4:12C201, K4:12C305, K4:12D101, K4:12E301, K4:12H101, K4:12H201, K4:12J301, K4:12K204",
    "locations": "Butik, Reception, Lgh 2, Polisstation, Övningsmiljö Parkbänk, Lgh 3, Övningsmiljö Gågata, Grepphall, Övningsmiljö Trapphus, Pub, Lgh 3, Start/Skytterum, Flexrum, FX-lägenhet, FX-lägenhet",
    "type": "PDV",
    "momentText": "Dag 2. Tillämpningsövning",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-100",
    "sourceRow": 100,
    "week": 51,
    "weekday": "Torsdag",
    "date": "2026-12-17",
    "startTime": "08:15",
    "endDate": "2026-12-17",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2, KR:1120N2, KR:1203E2, KR:1207E2",
    "locations": "Radiosal, Radiosal, Lärosal, Lärosal",
    "type": "Omexamination 1",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-101",
    "sourceRow": 101,
    "week": 51,
    "weekday": "Torsdag",
    "date": "2026-12-17",
    "startTime": "10:15",
    "endDate": "2026-12-17",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0, KR:1012K3",
    "locations": "Skjutbana, Skjutbana",
    "type": "Omexamination 1",
    "momentText": "",
    "momentNumber": "5:9",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-102",
    "sourceRow": 102,
    "week": 51,
    "weekday": "Torsdag",
    "date": "2026-12-17",
    "startTime": "13:15",
    "endDate": "2026-12-17",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "KR:102001, KR:1103K5",
    "locations": "Lgh 3, Lärosal",
    "type": "Dödsbudsövning",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-103",
    "sourceRow": 103,
    "week": 51,
    "weekday": "Fredag",
    "date": "2026-12-18",
    "startTime": "08:15",
    "endDate": "2026-12-18",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0, KR:1012K3",
    "locations": "Skjutbana, Skjutbana",
    "type": "Resurstid 2",
    "momentText": "",
    "momentNumber": "5:10",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-104",
    "sourceRow": 104,
    "week": 51,
    "weekday": "Fredag",
    "date": "2026-12-18",
    "startTime": "10:15",
    "endDate": "2026-12-18",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Brandövning",
    "course": "",
    "locationIds": "KR:1103K5",
    "locations": "Lärosal",
    "type": "Brandövning",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-105",
    "sourceRow": 105,
    "week": 51,
    "weekday": "Fredag",
    "date": "2026-12-18",
    "startTime": "13:15",
    "endDate": "2026-12-18",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Rättssäker dokumentation DURTvå",
    "course": "Rättssäker dokumentation DURTvå",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Examination",
    "momentText": "",
    "momentNumber": "17",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-106",
    "sourceRow": 106,
    "week": 52,
    "weekday": "Torsdag",
    "date": "2026-12-24",
    "startTime": "00:00",
    "endDate": "2026-12-25",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Julafton",
    "title": "Julafton",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-107",
    "sourceRow": 107,
    "week": 52,
    "weekday": "Fredag",
    "date": "2026-12-25",
    "startTime": "00:00",
    "endDate": "2026-12-26",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Juldagen",
    "title": "Juldagen",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-108",
    "sourceRow": 108,
    "week": 52,
    "weekday": "Lördag",
    "date": "2026-12-26",
    "startTime": "00:00",
    "endDate": "2026-12-27",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Annandag jul",
    "title": "Annandag jul",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-109",
    "sourceRow": 109,
    "week": 53,
    "weekday": "Torsdag",
    "date": "2026-12-31",
    "startTime": "00:00",
    "endDate": "2027-01-01",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Nyårsafton",
    "title": "Nyårsafton",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-110",
    "sourceRow": 110,
    "week": 53,
    "weekday": "Fredag",
    "date": "2027-01-01",
    "startTime": "00:00",
    "endDate": "2027-01-02",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Nyårsdagen",
    "title": "Nyårsdagen",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-111",
    "sourceRow": 111,
    "week": 1,
    "weekday": "Onsdag",
    "date": "2027-01-06",
    "startTime": "00:00",
    "endDate": "2027-01-07",
    "endTime": "00:00",
    "allDay": true,
    "groups": [],
    "audience": "Trettondedag jul",
    "title": "Trettondedag jul",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "holiday"
  },
  {
    "id": "te-112",
    "sourceRow": 112,
    "week": 2,
    "weekday": "Måndag",
    "date": "2027-01-11",
    "startTime": "08:15",
    "endDate": "2027-01-11",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0, KR:1012K3",
    "locations": "Skjutbana, Skjutbana",
    "type": "Omexamination 2",
    "momentText": "",
    "momentNumber": "5:11",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-113",
    "sourceRow": 113,
    "week": 2,
    "weekday": "Måndag",
    "date": "2027-01-11",
    "startTime": "10:15",
    "endDate": "2027-01-11",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012D0",
    "locations": "Simulatorskjutning",
    "type": "Simulator",
    "momentText": "",
    "momentNumber": "5:12",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-114",
    "sourceRow": 114,
    "week": 2,
    "weekday": "Måndag",
    "date": "2027-01-11",
    "startTime": "13:15",
    "endDate": "2027-01-11",
    "endTime": "14:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Lektion",
    "momentText": "Lågfart med minibuss och släp",
    "momentNumber": "15",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-115",
    "sourceRow": 115,
    "week": 2,
    "weekday": "Måndag",
    "date": "2027-01-11",
    "startTime": "14:00",
    "endDate": "2027-01-11",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Lågfart med minibuss och släp",
    "momentNumber": "15",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-116",
    "sourceRow": 116,
    "week": 2,
    "weekday": "Måndag",
    "date": "2027-01-11",
    "startTime": "15:15",
    "endDate": "2027-01-11",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1012D0",
    "locations": "Simulatorskjutning",
    "type": "Simulator",
    "momentText": "",
    "momentNumber": "5:12",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-117",
    "sourceRow": 117,
    "week": 2,
    "weekday": "Tisdag",
    "date": "2027-01-12",
    "startTime": "08:15",
    "endDate": "2027-01-12",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "KR:1002H0, KR:1006N4, KR:101201, KR:102001, KR:1128N2, KR:1211G1, KR:1222H1",
    "locations": "Utsättningsrum, Arrest, Pub, Lgh 3, RLC-rum, Öppen yta, Lärosal / ALC",
    "type": "Slutövning",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-118",
    "sourceRow": 118,
    "week": 2,
    "weekday": "Onsdag",
    "date": "2027-01-13",
    "startTime": "08:15",
    "endDate": "2027-01-13",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Professionsutveckling",
    "course": "Professionsutveckling",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Avrapportering, Slutövning",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-119",
    "sourceRow": 119,
    "week": 2,
    "weekday": "Onsdag",
    "date": "2027-01-13",
    "startTime": "08:15",
    "endDate": "2027-01-13",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Rättssäker dokumentation DURTvå",
    "course": "Rättssäker dokumentation DURTvå",
    "locationIds": "KR:1114N2",
    "locations": "Datorsal",
    "type": "Omexamination 1",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-120",
    "sourceRow": 120,
    "week": 2,
    "weekday": "Onsdag",
    "date": "2027-01-13",
    "startTime": "13:15",
    "endDate": "2027-01-13",
    "endTime": "15:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0, KR:1012K3",
    "locations": "Skjutbana, Skjutbana",
    "type": "Lektion",
    "momentText": "Skydd/Skyl",
    "momentNumber": "5:13",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-121",
    "sourceRow": 121,
    "week": 2,
    "weekday": "Onsdag",
    "date": "2027-01-13",
    "startTime": "15:15",
    "endDate": "2027-01-13",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Sambandstjänst",
    "course": "Sambandstjänst",
    "locationIds": "KR:1118N2, KR:1120N2, KR:1203E2, KR:1207E2",
    "locations": "Radiosal, Radiosal, Lärosal, Lärosal",
    "type": "Omexamination 2",
    "momentText": "",
    "momentNumber": "",
    "examInfo": "",
    "category": "examination"
  },
  {
    "id": "te-122",
    "sourceRow": 122,
    "week": 2,
    "weekday": "Torsdag",
    "date": "2027-01-14",
    "startTime": "08:15",
    "endDate": "2027-01-14",
    "endTime": "12:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1006N4, KR:102501, KR:1027L1",
    "locations": "Arrest, Lgh 2, Garage",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:9",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-123",
    "sourceRow": 123,
    "week": 2,
    "weekday": "Torsdag",
    "date": "2027-01-14",
    "startTime": "13:15",
    "endDate": "2027-01-14",
    "endTime": "14:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "KR:1221B1",
    "locations": "Grupprum",
    "type": "Lektion",
    "momentText": "Lågfart med minibuss och släp",
    "momentNumber": "15",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-124",
    "sourceRow": 124,
    "week": 2,
    "weekday": "Torsdag",
    "date": "2027-01-14",
    "startTime": "13:15",
    "endDate": "2027-01-14",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG3",
      "BG4"
    ],
    "audience": "DP132A-HT2025-DP132-Bg3, DP132A-HT2025-DP132-Bg4",
    "title": "Polkon FTM",
    "course": "Polkon FTM",
    "locationIds": "KR:1006N4, KR:102501, KR:1027L1",
    "locations": "Arrest, Lgh 2, Garage",
    "type": "Lektion",
    "momentText": "",
    "momentNumber": "5:9",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-125",
    "sourceRow": 125,
    "week": 2,
    "weekday": "Torsdag",
    "date": "2027-01-14",
    "startTime": "14:00",
    "endDate": "2027-01-14",
    "endTime": "17:00",
    "allDay": false,
    "groups": [
      "BG1",
      "BG2"
    ],
    "audience": "DP132A-HT2025-DP132-Bg1, DP132A-HT2025-DP132-Bg2",
    "title": "PNF",
    "course": "PNF",
    "locationIds": "",
    "locations": "",
    "type": "Lektion",
    "momentText": "Lågfart med minibuss och släp",
    "momentNumber": "15",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-126",
    "sourceRow": 126,
    "week": 2,
    "weekday": "Fredag",
    "date": "2027-01-15",
    "startTime": "08:15",
    "endDate": "2027-01-15",
    "endTime": "10:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Polkon Vapen",
    "course": "Polkon Vapen",
    "locationIds": "KR:1009F0, KR:1012K3",
    "locations": "Skjutbana, Skjutbana",
    "type": "Lektion",
    "momentText": "Dolt bärande",
    "momentNumber": "5:14",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-127",
    "sourceRow": 127,
    "week": 2,
    "weekday": "Fredag",
    "date": "2027-01-15",
    "startTime": "10:15",
    "endDate": "2027-01-15",
    "endTime": "12:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132",
    "title": "Inlämning av uniformsutrustning. Utlämning av aspirantuniform",
    "course": "",
    "locationIds": "KR:1021B4",
    "locations": "Uniformsförråd",
    "type": "Inlämning",
    "momentText": "Inlämning av uniformsutrustning. Utlämning av aspirantuniform",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  },
  {
    "id": "te-128",
    "sourceRow": 128,
    "week": 2,
    "weekday": "Fredag",
    "date": "2027-01-15",
    "startTime": "13:00",
    "endDate": "2027-01-15",
    "endTime": "17:00",
    "allDay": false,
    "groups": [],
    "audience": "DP132A-HT2025-DP132, PO141C-HT2026-141CA, PO141C-HT2026-141DI",
    "title": "Examen",
    "course": "",
    "locationIds": "",
    "locations": "",
    "type": "",
    "momentText": "Examen",
    "momentNumber": "",
    "examInfo": "",
    "category": "teaching"
  }
];
